name: Deploy Backend AWS

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir imagen Docker
        run: docker build -t jessy1707/backend-despacho ./Springboot-API-REST-DESPACHO

      - name: Subir imagen Docker Hub
        run: docker push jessy1707/backend-despacho

      - name: Deploy en EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo docker stop backend-despacho || true
            sudo docker rm backend-despacho || true
            sudo docker pull jessy1707/backend-despacho

            sudo docker run -d -p 8081:8081 \
            --name backend-despacho \
            jessy1707/backend-despacho



        